### ISSUE TITLE
Verta::getRial()

### ISSUE THREAD

**Issue by miladganjali** [hekmatinasser/verta#1]
Hi
this method is removed from your package?
> `Call to undefined method Hekmatinasser\Verta\Verta::getRial() `

**Comment by hekmatinasser** [comment]
Hi yes remove in new version and in seprate package

**Comment by miladganjali** [comment]
Hi my friend thanks for quick response 
please do not remove any method from your packages because by removing someone work going to hell by that,
 Why?
Because after update all site call that error. 
 I get your old code by old composer catch 

Thanks for your work and keep up your sprite in opensource

**Comment by hekmatinasser** [comment]
change to word methods different nature jalali calendar
notowo is multi language and very strong same as change to word methods verta

**Comment by hekmatinasser** [comment]
package notowo now realese 1.0 version. you can use with [packagist](https://packagist.org/packages/hekmatinasser/notowo) and read document.
