### ISSUE TITLE
خارج کردن هفته

### ISSUE THREAD

**Issue by adam1442** [hekmatinasser/verta#10]
سلام ببخشید آیا میشه با این پیچ هفته رو در آورد؟؟
مثلا من یک سری اطلاعات داخل دیتابیس دارم و می خوام بیام این اطلاعات رو هفته به هفته در بیارم مثلا تعداد خودرو ثبت شده در هفته گذشته و تعداد خودرو ثبت شده در این هفته آیا متودی داره که بتونم هفته رو تشخص بدم و این کاری که گفتم انجام بدم؟؟؟؟

**Comment by hekmatinasser** [comment]
سلام 
بله شما میتونید تاریخ ابتدا هفته گذشته رو بدست بیارید و در کویری خود در یک بازه جستجو کنید
`subWeek()`

این متد از تاریخ شما یک هفته کم میکنه  و تابع های دیگری در مورد هفته داره امیدوارم کمکمتون کنه

**Comment by adam1442** [comment]
@hekmatinasser بسیار سپاس گذارم از پاسخی که دادید و این که در سریع ترین زمان ممکن پاسیخ دادید و قابل تقدیره
