### ISSUE TITLE
مشکل در تبدیل تاریخ

### ISSUE THREAD

**Issue by Azare77** [hekmatinasser/verta#100]
من موقع استفاده از این پکیج متوجه خطای تبدیل تاریخ 15-04-1998 شدم که به جای 26 فروردین تاریخ 25 فروردین را برمیگرداند

**Comment by hekmatinasser** [comment]
تست شد 
    return new Hekmatinasser\Verta\Verta('1998-04-15');
1377-01-26 00:00:00
مواردی مانند تایم زون و تنظیمات پروژه را بررسی کنید

**Comment by Azare77** [comment]
موضوع مربوط به آرایه dates مربوط به مدل بود
اگه اسم فیلدی توی اون آرایه باشه متاسفانه مشکلاتی رو ایجاد میکنه

سپاسگزارم

در تاریخ یکشنبه ۶ ژوئن ۲۰۲۱،‏ ۱۷:۵۷ hekmatinasser ***@***.***>
نوشت:
