### ISSUE TITLE
Class 'Hekmatinasser\Verta\VertaServiceProvider' not found

### ISSUE THREAD

**Issue by asadghazanfary** [hekmatinasser/verta#101]
سلام

من از لاراول نسخه 8 و از پی اچ پی 7.4.5 استفاده میکنم

پکیج رو نصب کردم و تو لیست پروایدرها اضافه کردم

اما با همچین پیغامی روبرو میشم

![Capture](https://user-images.githubusercontent.com/5650939/120940269-a45fd180-c731-11eb-9f63-4f26000d52c5.JPG)

البته باید بگم که این پکیج قبلا درست کار میکرد اما حالا نمیدونم چرا همچین مشکلی بوجود امد

ممنون میشم برای حل این مشکل کمکم کنید

**Comment by iamamirsalehi** [comment]
سلام،‌بله بنده هم از امروز صبح همچین خطایی رو دارم همچین اروری رو میگیرم

**Comment by iamamirsalehi** [comment]
فکر کنم شما هم زدید تا پکیج ها آپدیت بشن. به ورژن قبلی این پکیج برگردید تا فعلا مشکل حل بشه و دوستان مشکل ورژن جدید رو حل کنن

**Comment by mohammad-salehnia** [comment]
سلام منم همین مشکلو دارم ورژن های قبلیشم نصب می کنم بازم درست نمیشه از لاراول 6 هم استفاده کردم

**Comment by asadghazanfary** [comment]
من همونطور که دوست عزیز @iamamirsalehi  گفت برگشتم به نسخه قبلی و مشکل برطرف شد.
