### ISSUE TITLE
Undefined index: year_months

### ISSUE THREAD

**Issue by farsh4d** [hekmatinasser/verta#102]
Verta::parse('1399-06-30')->format('Y/m/d') caused this error:
Undefined index: year_months at verta/src/Traits/Creator.php:144

laravel v 5.5
php v 7.4

**Comment by masoodvahid** [comment]
من هم بعد از آپدیت به آخرین ورژن این مشکل رو دارم. فعلا برگشتم به نسخه قبلی.

**Comment by sonqor** [comment]
Same issue.
Please fix the code ASAP.

**Comment by hekmatinasser** [comment]
fix bug in new version
