### ISSUE TITLE
Error in validator

### ISSUE THREAD

**Issue by Azare77** [hekmatinasser/verta#103]
"message": "Access to undeclared static property Hekmatinasser\\Verta\\Laravel\\JalaliValidator::$messages",
    "exception": "Error",
    "file": "*/vendor/hekmatinasser/verta/src/Laravel/JalaliValidator.php",
    "line": 212,

work fine last time but now i have an Error

**Comment by hekmatinasser** [comment]
fix in v1.12.2

**Comment by Azare77** [comment]
thanks but there is an other bug 

whit field birthdate => 1400/3/26 
i have this error

{
    "message": "The given data was invalid.",
    "errors": {
        "birthdate": [
            "validation.jdate"
        ]
    }
}

**Comment by hmoradian** [comment]
khodavalkili khodetoon test mikonid package ro?!!!

**Comment by hekmatinasser** [comment]
> thanks but there is an other bug
> 
> whit field birthdate => 1400/3/26
> i have this error
> 
> {
> "message": "The given data was invalid.",
> "errors": {
> "birthdate": [
> "validation.jdate"
> ]
> }
> }
در نسخه 1.12.3 برطرف شد
شما باید از مسیر پوشه زبان به فایل  ارور های اعتبار سنجی را به پروزه خود اضافه کنید  تا ارور فارسی مشاهده کنید
