### ISSUE TITLE
Class "Hekmatinasser\Verta\VertaServiceProvider" not found 

### ISSUE THREAD

**Issue by ferasat** [hekmatinasser/verta#104]
سلام . 
پکیج را روی پروژه نصب کرده بودم .
حالا داره این ارور را میده و نمی گزاره پروژه ران شود 
`In ProviderRepository.php line 208:

  Class "Hekmatinasser\Verta\VertaServiceProvider" not found `

**Comment by erfantkerfan** [comment]
منم امروز این ارور رو خوردم

**Comment by erfantkerfan** [comment]
> سلام .
> پکیج را روی پروژه نصب کرده بودم .
> حالا داره این ارور را میده و نمی گزاره پروژه ران شود
> `In ProviderRepository.php line 208:
> 
> Class "Hekmatinasser\Verta\VertaServiceProvider" not found `

https://github.com/hekmatinasser/verta/issues/101#issuecomment-857941158

**Comment by ferasat** [comment]
@erfantkerfan 
دمت گرم که خبر دادی .
پس راحل حل شده این :
در فایل app.php :

Hekmatinasser\Verta\Laravel\VertaServiceProvider::class,
در providers

و :

در aliases :

'Verta' => Hekmatinasser\Verta\Laravel\VertaServiceProvider::class,

را جایگزین کنیم .
