### ISSUE TITLE
Unknown datetime

### ISSUE THREAD

**Issue by vhdm** [hekmatinasser/verta#105]
سلام و تشکر از زحمات شما، ممنون میشم دلیل این ارور رو بگین دو روزه لنگ این شدم
![image](https://user-images.githubusercontent.com/14149777/130479667-06ebd4da-b1d3-4446-ac36-6d54084a6283.png)

**Comment by hekmatinasser** [comment]
سلام این ارور زمانی اتفاق میوفته که تاریخ ورودی که دادید صحیح نیست 
بررسی کنید چه تاریخی دارید به ورودی تابه ورتا میدید

**Comment by vhdm** [comment]
ممنون حل شد
