### ISSUE TITLE
jalali to georgian

### ISSUE THREAD

**Issue by Mohamadmr** [hekmatinasser/verta#106]
how can I convert Jalali date to Georgian date by passing string?
example "1400/06/09 15:21:49" => "2021-08-31 15:21:49"

**Comment by Mohamadmr** [comment]
> how can I convert Jalali date to Georgian date by passing string?
> example "1400/06/09 15:21:49" => "2021-08-31 15:21:49"

Verta::parse("1400/06/09 15:21:49")->datetime()->format('Y-m-d H:i:s')

**Comment by hekmatinasser** [comment]
also 
Verta::parse("1400/06/09 15:21:49")->formatGregorian('Y-m-d H:i:s')
