### ISSUE TITLE
اشکال در محاسبه هفته 

### ISSUE THREAD

**Issue by AngusDV** [hekmatinasser/verta#112]
>>> verta()->parse('1400-11-16')->weekOfYear
=> 46
>>> verta()->parse('1400-11-16')->startWeek()
=> Hekmatinasser\Verta\Verta @1644019200 {#4822
     date: 1400-11-16 00:00:00.0 UTC (+00:00),
   }
>>> verta()->parse('1400-11-16')->endWeek()
=> Hekmatinasser\Verta\Verta @1644623999 {#4832
     date: 1400-11-22 23:59:59.0 UTC (+00:00),
   }
>>> verta()->parse('1400-11-14')->weekOfYear
=> 46

**Comment by hekmatinasser** [comment]
مورد در نسخه جدید 1.12.6 مرتفع شد
