### ISSUE TITLE
php 8.1 deprecation

### ISSUE THREAD

**Issue by mziraki** [hekmatinasser/verta#113]
https://github.com/hekmatinasser/verta/blob/5bf4395e9b90c18c0ca93acd11675ec0fe4db2d6/src/Traits/Transformation.php#L96

problem:
"Implicit conversion from float to int loses precision" warning

solution:
https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

**Comment by hekmatinasser** [comment]
fix in new version 1.12.7
or use v2
