### ISSUE TITLE
php 8.1 DateTime's method return types

### ISSUE THREAD

**Issue by mziraki** [hekmatinasser/verta#115]
php 8.1 DateTime class method signatures has been changed:
https://www.php.net/manual/en/class.datetime
there are now strict return types for DateTime methods.

warning examples:
Return type of Hekmatinasser\Verta\Traits\Date::setDate($year, $month, $day) should either be compatible with DateTime::setDate(int $year, int $month, int $day): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/hekmatinasser/verta/src/Traits/Accessor.php on line 245

Return type of Hekmatinasser\Verta\Traits\Date::format($format) should either be compatible with DateTime::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/hekmatinasser/verta/src/Traits/Formatting.php on line 328

**Comment by hekmatinasser** [comment]
fix bug new version

**Comment by mziraki** [comment]
@hekmatinasser 
issue still exists in v2.0.2

Return type of Hekmatinasser\Verta\Traits\Date::setDate($year, $month, $day) should either be compatible with DateTime::setDate(int $year, int $month, int $day): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/hekmatinasser/verta/src/Traits/Accessor.php on line 245

php 8.1 DateTime return types are not compatible with older versions of PHP, in general there are lots of breaking changes in php 8.1, at some point you must drop support for earlier of php or like some packages create 2 separate branches for php < 8.1 and >= 8.1

**Comment by hekmatinasser** [comment]
setDate function replace with setDateJalali

return type not compatible with DateTime php ,

**Comment by mziraki** [comment]
@hekmatinasser 
hi, thanks for the fix but:

Return type of Hekmatinasser\Verta\Traits\Date::format($format) should either be compatible with DateTime::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/hekmatinasser/verta/src/Traits/Formatting.php on line 328

you reverted back the format method signature and caused the warning above.

one more thing, plz release new versions of package with new versioning, packagist do not update automatically already created tag, and it's not a good practice overall.

thanks.

**Comment by mziraki** [comment]
@hekmatinasser
PR https://github.com/hekmatinasser/verta/pull/119 for this issue & few more improvements
