### ISSUE TITLE
استفاده داخل لاراول

### ISSUE THREAD

**Issue by sajjadkazemi10ss** [hekmatinasser/verta#12]
من میخوام تاریخ شمسی رو از کاربر بگیرم و به صورت میلادی توی دیتابیس ثبت کنم
از دستو زیر استاده می کنم
البته داخل کنترلر store به صورت زیر
```
'Expiration_date' =>Verta::getGregorian($request->datex)
```
اما خطای زیر رو میده
```
Too few arguments to function Hekmatinasser\Verta\Verta::getGregorian(), 1 passed in
```

**Comment by hekmatinasser** [comment]
باسلام تابع که استفاده کردید سه پارامتر میخواد که سال ماه و روز

توصیه من استفاده از تابع پارس هست

`'Expiration_date' => Verta::parse($request->datex);`

**Comment by sajjadkazemi10ss** [comment]
خروجی که بهم میده فارسی هست اعدادش
میخوام انگلیبسی باشه
باید چیکار کنم

**Comment by hekmatinasser** [comment]
formatGregorian برای تبدیل به فرمت انگلیسی استفاده نمی شود

**Comment by dariushzamani** [comment]
سلام 
میشه دستور کلی را بنویسید - من هم همین مشکل را دارم می خواهم تاریخ شمسی که از datepicker فارسی گرفتم را به صورت میلادی در دیتابیس ثبت کنم

**Comment by dariushzamani** [comment]
من هم همین مشکل را دارم می خواهم تاریخ شمسی که از
datepicker 
فارسی گرفتم را به صورت میلادی در دیتابیس ثبت کنم

**Comment by hekmatinasser** [comment]
$date = Verta::parse($request->datex);
return $date->formatGregorian('...');

**Comment by dariushzamani** [comment]
سلام 
ببخشید یک آرایه می دهد که برای تبدیل به فرمت تاریخ نمی دانم باید چه کاری انجام بدهم
