### ISSUE TITLE
مشکل نامشخص در استفاده از پکیج

### ISSUE THREAD

**Issue by saeedasadib** [hekmatinasser/verta#120]
سلام،
من موقع استفاده از پکیج این ارور رو میگیرم.

Declaration of Hekmatinasser\Verta\Traits\Date::format(string $format): string must be compatible with DateTime::format($format)

**Comment by erfantkerfan** [comment]
php, laravel and package version please!

**Comment by mziraki** [comment]
@saeedasadib @erfantkerfan PR #119 will fix it

**Comment by amirahmadihr** [comment]
منم همین خطا رو میگیرم . 
"php": "^7.3|^8.0",
"hekmatinasser/verta": "^2.0",
"laravel/framework": "^8.75",

**Comment by hekmatinasser** [comment]
درست شد
