### ISSUE TITLE
تغییر ساعت در برنامه

### ISSUE THREAD

**Issue by maziyaryosofi** [hekmatinasser/verta#121]
سلام
وقت شما بخیر

ساعت سرور و لاراول بر روی Asia/Tehran ست شده است. در دیتابیس ساعت به صورت 2022-02-23 20:52:12 ذخیره شده هنگام تبدیل در ورتا به صورت 1400/12/4 17:22 نمایش داده می شود. این اختلاف زمان در تمامی تبدیل ها وجود دارد. چگونه می توان این مورد را مرتفع نمود؟

**Comment by mziraki** [comment]
@maziyaryosofi @hekmatinasser PR https://github.com/hekmatinasser/verta/pull/119 will fix it
