### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by samsesh** [hekmatinasser/verta#122]
موقع نصب با این مشکل برخورد میکنم 
  Class "Hekmatinasser\Verta\Laravel\VertaServiceProvider" not found

**Comment by hekmatinasser** [comment]
لطفا نسخه لاراول خود و پی اچ پی خود را بنویسید تست کردم مشکلی برای نصب وجود نداشت

**Comment by hekmatinasser** [comment]
مجددا با نسخه لاراول مربوطه نصب کردم نصب شد مسیر و کلاس مربوطه وجود دارد
