### ISSUE TITLE
Ago and after are printed reverse in formatDifference

### ISSUE THREAD

**Issue by aminhd2658** [hekmatinasser/verta#124]
Hello.
when I use `formatDifference`, ago and after is displayed in reverse in Persian(fa) lang. I don't know for other languages but if some codes changes, this problem will be solved.
I think:

File: hekmatinasser\verta\traits\Formatting.php
Line: 416

It should be written like this: 
        `$absolute = static::$messages['phrase'][$difference < 0 ? 'ago' : 'later'];`

**Comment by hekmatinasser** [comment]
hello tnx

**Comment by aminhd2658** [comment]
Sorry. issue updated.(formatDifference have problem)

**Comment by aminhd2658** [comment]
> hello tnx

Sorry. issue updated.(formatDifference have problem)

**Comment by hekmatinasser** [comment]
check formatDifference and in language fa
you can change direction 
![image](https://user-images.githubusercontent.com/17121789/163141944-cc42d6f3-3f4b-4f6e-b96d-de2de9c275e2.png)
