### ISSUE TITLE
Laravel 9 and php 8.1

### ISSUE THREAD

**Issue by sajjadgol** [hekmatinasser/verta#125]
واسه php8.1  یک خطا میده 

PHP Deprecated:  Return type of Hekmatinasser\Verta\Traits\Date::setDate($year, $month, $day) should either be compatible with DateTime::setDate(int $year, int $month, int $day): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/project1/vendor/hekmatinasser/verta/src/Traits/Accessor.php on line 245
PHP Deprecated:  Return type of Hekmatinasser\Verta\Traits\Date::format($format) should either be compatible with DateTime::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/project1/vendor/hekmatinasser/verta/src/Traits/Formatting.php on line 328

**Comment by hekmatinasser** [comment]
سلام

**Comment by hekmatinasser** [comment]
سلام از نسخه جدید استفاده کنید . تابع setDateJalali افزوده شده

**Comment by matinwd** [comment]
سلام همین مشکل رو روی ورژن ۳.۸ دارم هنوز مرتفع نشده.

laravel 10
php 8.2.0
