### ISSUE TITLE
مشکل در نیمه دوم سال

### ISSUE THREAD

**Issue by Abedi98** [hekmatinasser/verta#126]
سلام وقت بخیر
 خروجی کد زیر :
```
$v4 = verta();
$v4->month = 6;
dd($v4);

Hekmatinasser\Verta\Verta @1663836219 {#1552 ▼
  date: 1401-06-31 12:13:39.0 Asia/Tehran (+03:30)
}
```

حالا خروجی کد برای نیمه دوم سال 

```
$v4 = verta();
$v4->month = 7;
dd($v4);

Hekmatinasser\Verta\Verta @1666514667 {#1552 ▼
  date: **1401-08-01** 12:14:27.0 Asia/Tehran (+03:30)
}
```

وقتی ماه رو روی نیمه دوم سال ست میکنم 1 ماه میره جلو

**Comment by Abedi98** [comment]
الان هم پکیج رو آپدیت کردم و کد زیر رو اجرا میکنم :

```
$v4 = verta();
$v4->year(1400);
$v4->month(7);
$v4->day(10);
return $v4;

output : 1400-02-10 12:38:46
```

سال و روز با توجه به تغییراتی که دادم اعمال شده ولی ماه رو همچنان ماه جاری نمایش میده و تغییر پیدا نمیکنه به ماه 7

**Comment by hekmatinasser** [comment]
سلام در ورتا افزایش ماه با سرریز است  و اگر از تعداد روز های ماه بیشتر بشه ماه جلو میبره 
تابعی برای افزایش ماه بدون سرریز شدن اضافه میکنم
