### ISSUE TITLE
TypeError now()->formatWord

### ISSUE THREAD

**Issue by LabSilo** [hekmatinasser/verta#132]
Hello, 
I expect `Verta::now()->formatWord('l dS F');` to work but it throws TypeError
`TypeError : Hekmatinasser\Jalali\Jalali::now(): Return value must be of type Hekmatinasser\Verta\Verta, Hekmatinasser\Jalali\Jalali returned`

While `verta()->formatWord('l dS F');` works, using the facade above doesn't work and `Verta::formatWord('l dS F');` throws `Error : Non-static method Hekmatinasser\Jalali\Jalali::formatWord() cannot be called statically`

**Comment by hekmatinasser** [comment]
tnx for issues
fix now in new version, please update

**Comment by LabSilo** [comment]
Unfortunately, not.
Actually not because your fix is wrong, but because the version you published in packagist doesn't have the change and is just identical to v8.1.1.

https://github.com/hekmatinasser/jalali/tree/v8.1.2 tag is created on top of `master` branch instead of `8.x`.

**Comment by LabSilo** [comment]
@hekmatinasser I see you have created another tag named v8.1.3 which is still the same!
Please create a tag and release in [https://github.com/hekmatinasser/jalali](Jalali repo.) called v8.1.4 on top of it's 8.x branch.
Then do the same in this repository.
