### ISSUE TITLE
saving verta object error

### ISSUE THREAD

**Issue by mmoghadam11** [hekmatinasser/verta#134]
im using mongo db and need save verta time in that. but it saves null object
so i think its better to save it as timestamp
how can i change verta object to timestamp???

i used `$vertaOBJ->timestamp` it gives timestamp but when i parse it to verta again....`verta($vertaOBJ->timestamp)` it gives me  that time (-04:30) earlier 

```
^ Hekmatinasser\Verta\Verta @1661196600 {#323 ▼
  date: 1401-06-01 00:00:00.0 Asia/Tehran (+04:30)
}
^ 1661196600
^ Hekmatinasser\Verta\Verta @1661196600 {#322 ▼
  date: 1401-05-31 19:30:00.0 +00:00
}
```
seems its for time zone setting in app.php : `'timezone' => 'Asia/Tehran'`
how can i handle this???

**Comment by hekmatinasser** [comment]
better convert verta to carbon and save in mongodb
$vertaOBJ->toCarbon();

please update to last version for timezone
