### ISSUE TITLE
تنظیمات نصب دستی

### ISSUE THREAD

**Issue by golkarm58** [hekmatinasser/verta#137]
با سلام و عرض ادب
با توجه به محدودیت شدید اینترنت امکان نصب با دستورات artisan وجود نداره و ارور میده.آیا امکان انجام تنظیمات لازم به صورت دستی برای نصب وجود داره؟

**Comment by hekmatinasser** [comment]
با سلام 
برای نصب دستی این روش وجود دارد اما توصیه نمیکنم بهتر از از وی پی ان برای نصب استفاده کنید
[https://stackoverflow.com/questions/45566233/laravel-how-to-manually-install-package-without-composer](url)

**Comment by golkarm58** [comment]
سپاسگزارم 

⁣Sent from BlueMail ​
