### ISSUE TITLE
remove `toCarbon` method in new version

### ISSUE THREAD

**Issue by mohamadtsn** [hekmatinasser/verta#138]
It seems that the "toCarbon" method does not exist in the new version and it has become a problem.

**Comment by hekmatinasser** [comment]
[https://github.com/hekmatinasser/verta/blob/8.x/src/Verta.php](url)

**Comment by mohamadtsn** [comment]
This method (`toCarbon`) is not available from version 8.1.6 seems to have been removed.
https://github.com/hekmatinasser/verta/blob/master/src/Verta.php
Or
https://github.com/hekmatinasser/verta/blob/v8.1.6/src/Verta.php

While according to you, this method is available in the previous version (8.1.5).
https://github.com/hekmatinasser/verta/blob/v8.1.5/src/Verta.php

**Comment by arbabi2010** [comment]
@hekmatinasser 
من هم الان نصب کردم , و نسخه هم 8.1 هست . خطای زیر رو بهم میده

**Comment by arbabi2010** [comment]
@hekmatinasser 
فکر میکنم نسخه های اخیر ایراد زیاد داره . من اومدم روی نسخه 8.1.5 و این کد رو اجرا کردم 
`Verta::parse("1401/08/25")->timezone("Asia/Tehran")->toCarbon()`
خروجی که نشون میده 
"2022-11-15T20:30:00.000000Z"
در حالی که باید 16-11-2022 رو نشون بده
