### ISSUE TITLE
مشکل در متد isToday() 

### ISSUE THREAD

**Issue by irandynamic** [hekmatinasser/verta#139]
سلام و وقت بخیر
در زمان فراخوانی متد isToday() خطای زیر رخ میده
Hekmatinasser\Jalali\Jalali::now(): Return value must be of type Hekmatinasser\Verta\Verta, Hekmatinasser\Jalali\Jalali returned

**Comment by hekmatinasser** [comment]
سلام این مورد احتمالا به دلیل اپدیت نبودن نسخه پکیج باشد چون در  اخرین نسخه تست شده 8 این مورد وجود ندارد

**Comment by irandynamic** [comment]
سلام مجدد
نسخه فعلی ^8.1 هست.

**Comment by irandynamic** [comment]
سلام مجدد
نسخه فعلی ^8.1 هست.

**Comment by hekmatinasser** [comment]
نسخه ورتا 8.1.6 اپدیت کنید این مورد رفع میشود

**Comment by irandynamic** [comment]
نسخه ای که داریم استفاده میکنیم همین آخرین نسخه ای هست که فرمودید ولی باز هم مشکل پابرجاست.

**Comment by celysium** [comment]
در تست و نصب این مورد باز هم تست شد نسخه جدید این مشکل را نداشت

**Comment by hekmatinasser** [comment]
در تست و نصب این مورد باز هم تست شد نسخه جدید این مشکل را ندارد
