### ISSUE TITLE
تغییر خود به خود تاریخ در هنگام گرفتن ابتدا و انتهای ماه ها

### ISSUE THREAD

**Issue by khanzadimahdi** [hekmatinasser/verta#14]
موقعی که میخوام ابتدا و انتهای یک ماه رو بگیرم وقتی انتهای ماه رو میگیرم تاریخ ابتدای ماه هم به انتهای ماه تغییر پیدا میکنه
حدس میزنم از اشاره گرها دارید استفاده میکنید که این مشکل رو به وجود اورده
``` php
    $v = verta();
    $v->month= 1;
    print_r( [$v->startMonth(),$v->endMonth()]);
   /* output:
       [
           0=>1397-01-31 00:00:00.0 Asia/Tehran (+03:30)
           1=>1397-01-31 00:00:00.0 Asia/Tehran (+03:30)
       ]
   */
```

**Comment by hekmatinasser** [comment]
سلام
پلاگین خود را اپدیت کنید به نسخه 1.9.6 از تابع کپی استفاده کنید

$v = verta();
    $v->month= 1;
    print_r([$v->copy()->startMonth(),$v->copy()->endMonth()]);
