### ISSUE TITLE
اشکال در محاسبه تاریخ

### ISSUE THREAD

**Issue by devbrisk** [hekmatinasser/verta#140]
سلام
اشکالی تو محاسبه تاریخ ها وجود داره. کد زیر :
```
$d1 = Verta::parse('1401-08-16')->formatGregorian('Y-m-d');
$d2 = new Verta("2022-11-06");
```

متغیر d1 تاریخ 2022-11-06 و برمیگردونه و دقیقا همون تاریخ و به d2 پاس میدیم تاریخ 1401-08-15 رو برمیگردونه

**Comment by irandynamic** [comment]
سلام
توی تنظیمات لاراول، timezone باید روی Asia/Tehran باشه

**Comment by devbrisk** [comment]
timezone روی Asia/Tehran هست و این مشکل و داریم

**Comment by irandynamic** [comment]
متغیر d2 مقدار رو درست برمیگردونه چون 1401-08-16 برابر با 2022-11-07 هست. پس در واقع d1 داره یه روز عقبتر برمیگردونه

**Comment by hekmatinasser** [comment]
$d1 = Verta::parse('1401-08-20')->formatGregorian('Y-m-d');
    $d2 = new Verta("2022-11-11");
    dd($d1,$d2);

"2022-11-11"
Hekmatinasser\Verta\Verta @1668112200 {#294 ▼
  date: 1401-08-20 00:00:00.0 Asia/Tehran (+03:30)
}

نسخه ورتا 81.6 اپدیت کنید این مورد رفع میشود

**Comment by devbrisk** [comment]
من از آخرین ورژن verta دارم استفاده می کنم ولی این مشکل و دارم کماکان

![Screenshot_1](https://user-images.githubusercontent.com/114703704/201432320-f9f36b6d-e9c2-423d-81f2-2a39776dc0e2.png)
![Screenshot_2](https://user-images.githubusercontent.com/114703704/201432323-faf582b8-ea38-4488-a4f4-d0f21b342aeb.png)

**Comment by hekmatinasser** [comment]
نسخه جدید پکیج اپدیت کنید 
در نسخه 8.1.5 hekmatinasser/jalali این مورد رفع شد
