### ISSUE TITLE
Undefined type 'Hekmatinasser\Verta\Verta'.

### ISSUE THREAD

**Issue by sinar93** [hekmatinasser/verta#141]
Hi
Thank you for your great package.

I am trying to use Verta in Laravel. My PHP intelephense is giving me a hard time:
![image](https://user-images.githubusercontent.com/2706721/201542081-1054ca0c-3ff2-4857-8f4c-590e96b445fa.png)

I include your package in my controller:
```
use Hekmatinasser\Verta\Verta;
```
but my intelephense keep tagging it like an error ```Undefined type 'Hekmatinasser\Verta\Verta'.``` not only in my controller but in the vendor folder too.

I was wondering if I am doing it the right way? Could you please provide a small example with Laravel?

Many thanks in advance

**Comment by hekmatinasser** [comment]
hi
thank you for use verta

please check and install again verta 

you can use helper function verta() for access object verta

**Comment by sinar93** [comment]
Thank you for your reply,
I couldn't use the helper function before, I have installed it again and its working fine now.
Thanks a lot
