### ISSUE TITLE
VertaServiceProvider not found

### ISSUE THREAD

**Issue by FarzinBidokhti** [hekmatinasser/verta#144]
Hi
I add this package in my project, after that I add two line in app.php:
```
Hekmatinasser\Verta\VertaServiceProvider::class,
'Verta' => Hekmatinasser\Verta\Verta::class,
```
 when I use Verta, I get this error:
` Class "Hekmatinasser\Verta\VertaServiceProvider" not found`
What's your solution to solve this item?
Thanks.

**Comment by hekmatinasser** [comment]
hi
you don't need provider in app config laravel project. add provider automatic when package discover.
but correct namespace provider to blow:
Hekmatinasser\Verta\Laravel\VertaServiceProvider::class
