### ISSUE TITLE
diffMonths محاسبه اشتباه در متد 

### ISSUE THREAD

**Issue by hdhamid1371** [hekmatinasser/verta#147]
برای اجرای تابع diffMonths در ماه ما بین سال مشکلی وجود ندارد اما این متد در ماه آخر سال و یکماه بعد سال به دلیل اینکه تاریخ میلادی دلیل مقایسه هست مقدار اشتباه بر میگرداند مثلا ...
t1 = 2022-12-22 00:00:00 -> تاریخ اول دیماه هست
t2 = 2023-01-21 00:00:00 -> تاریخ اول بهمن ماه است و اختلاف این دو رو صفر برمیگرداند..
verta(t1)->diffMonths(t2)

**Comment by hekmatinasser** [comment]
سلام
این مقایسه کاملا درست است و نتیججه باید صفر باشد زیرا بین تاریخ مبدا و تاریخ مقصد هنوز یک ماه کامل تکمیل نشده است.

**Comment by hdhamid1371** [comment]
یعنی فاصله تاریخ به شمسی  1-10-1401 00:00:00 با 1-11-1401 00:00:00 یکماه نیست ؟
اون موضوع که شما گفتید که "بین تاریخ مبدا و تاریخ مقصد هنوز یک ماه کامل تکمیل نشده است." مربوط به تاریخ میلادی هست نه شمسی

**Comment by hekmatinasser** [comment]
$t1 = \verta('2022-12-29');
$t2 = \verta('2023-01-29');
dd( $t1->diffMonths($t2));
//output : 1

**Comment by hekmatinasser** [comment]
بله در حال بررسی موضوع و حل این مورد هستم ممکن است زمانبر باشد و نیاز به تفییر بازنویسی مجدد باشد.

**Comment by hdhamid1371** [comment]
ممنون. برای حل موقت این مورد من از متد addDay چند روز به پارامتر و تاریخ دوم اضافه کردم و با متد diffMonth محاسبه اختلاف انجام دادم.
تشکر از شما

**Comment by hekmatinasser** [comment]
بابت گزارش این مورد تشکر میکنم. این مورد باعث شد به ریراداتی در برخی توابع دیگر هم پی ببرم در نسخه 8.1.9 فعلا این مورد برطرف شده است اما به زودی در نسخه 8.2 در بقیه توابع این مورد را حل خواهم کرد.
ممنون
