### ISSUE TITLE
Verta ignores config Timezone

### ISSUE THREAD

**Issue by CrawDance** [hekmatinasser/verta#148]
verta returns UTC datetime from timestamp however timezone is already set to Asia/Tehran in config file.

Laravel v: 9.1
Verta v: 8.1.18

I've already checked the fixed PR but it doesnt help.
thanks in advance

**Comment by hekmatinasser** [comment]
hi current my time system is 17 jan 14:55 and run     dd( verta()); with utc time zone in app.php result:
Hekmatinasser\Verta\Verta @1673954712 {#290 ▼
  date: 1401-10-27 11:25:12.382140 UTC (+00:00)
}
and with tehran timezone result
Hekmatinasser\Verta\Verta @1673954937 {#290 ▼
  date: 1401-10-27 14:58:55.031774 Asia/Tehran (+03:30)
}

is correct timezone
