### ISSUE TITLE
نمایش اشتباه روز تولد

### ISSUE THREAD

**Issue by progintYasin** [hekmatinasser/verta#151]
درود و عرض ادب و سپاس بابت پکیج بسیار عالی که ساختید.
وقتی addDay را برای isBirthDay میزارم بجای اینکه تولدهای فردا را نشون بده، تولد های دیروز را نشون میده.
`verta($r->birthday)->addDay()->isBirthday()`
توی ServiceProvider هم  Verta::setLocale('fa'); را گذاشتم بازم تغییری نکرد
اگر addDay را نزارم تولدهای امروز را درست نشون میده.

**Comment by hekmatinasser** [comment]
سلام و وقت بخیر 
برای مشاهده اینکه ایا تولد فردا هست  میتونید از کد زیر استفاده کنید 
Verta::tomorrow()->isBirthday($r->birthday)

**Comment by progintYasin** [comment]
بله درست شد
سپاس از راهنماییتون 👍
