### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by mjavadtatari** [hekmatinasser/verta#152]
Hi, I upgraded from Laravel 5 (PHP 7) to laravel 10 (PHP 8),
and also updated to "hekmatinasser/verta": "^8.1",

now getting this error: 
`Call to undefined method Hekmatinasser\Verta\Verta::setStringformat()`

please help me with this

**Comment by hekmatinasser** [comment]
hi 
replace setStringformat with setFormat function
