### ISSUE TITLE
مشکل نمایش در استفاده از diffDays

### ISSUE THREAD

**Issue by realrezamirzaei** [hekmatinasser/verta#159]
سلام هنگام استفاده از diffDays عدد بازگشتی همیشه مثبته و نمیشه تشخص داد که روز مشخص شده گذشته یا نه و اینکه یک روز قبل و بعد روز جاری رو هم 0 نمایش میده

**Comment by hekmatinasser** [comment]
سلام 
verta()->diffDays('2023-02-24', false) // -106
verta()->diffDays('2023-02-24') // 106

باید از ساعت روز جاری دقیقا یک روز کامل گذشته باشد

verta('2023-02-24 13:00:50')->diffDays('2023-02-23 13:00:50', false) // -1
verta('2023-02-24 13:00:50')->diffDays('2023-02-23 13:01:00', false) // 0
