### ISSUE TITLE
اشتباه نگارشی

### ISSUE THREAD

**Issue by mrostd** [hekmatinasser/verta#160]
وقت به‌خیر
من با استفاده از روش زیر تاریخ و روز هفته رو نمایش می‌دم:
`{{ verta($activeComment->created_at)->formatWord('l dS F') }}`
همه چیز خوبه، اما به‌نظر «دوم» به‌اشتباه «دوام» نوشته شده.
خروجی چنین چیزیه:

>  جمعه دوام تیر

 نگارش بالا درمورد یازده‌ام تا نوزده‌ام بدون مشکله، اما دوم (و احتمالا سوم) اشتباه نوشته می‌شه.

**Comment by hekmatinasser** [comment]
باسلام 
برای رفع مشکل از نسخه پیکیج hekmatinasser/jalali خود را به نسخه [x8.2.1](https://github.com/hekmatinasser/jalali/releases/tag/x8.2.1) اپدیت کنید
