### ISSUE TITLE
یک ساعت عقب بودن

### ISSUE THREAD

**Issue by amirhossein-ceh** [hekmatinasser/verta#166]
سلام خسته نباشید

وقتی verta()->format('Y-m-d H:i:s') رو میزنم ساعت رو یک ساعت عقب تر نشون میده.
در صورتی که تاریخ و ساعت سرور درست همین لحظه رو نشون میده.

**Comment by hekmatinasser** [comment]
سلام تست انجام شد 
متاسفانه این مورد مشاهده نشد
