### ISSUE TITLE
جلو بودن زمان

### ISSUE THREAD

**Issue by dalilyabolfazl** [hekmatinasser/verta#167]
سلام
من از نسخه 8.4 کتابخانه استفاده میکنم اما زمان رو یک ساعت جلو نشون می ده 
![Screenshot (57)](https://github.com/hekmatinasser/verta/assets/172113941/6ef84bc9-8ae0-4dc5-bc76-a5645b392b64)
![Screenshot (58)](https://github.com/hekmatinasser/verta/assets/172113941/391d3003-27b1-4f87-9aba-37cfe1e9e346)

**Comment by hekmatinasser** [comment]
این مورد به دلیل مغایرت ساعت جهانی با ساعت ایران هست
