### ISSUE TITLE
برگرداندن تاریخ میلادی

### ISSUE THREAD

**Issue by toomtoom** [hekmatinasser/verta#18]
با سلام.
خروجی کد
$v = new Verta();
به صورت میلادی هست!
{
        "date": "2018-10-13 12:42:39.000000",
        "timezone_type": 3,
        "timezone": "Asia/Tehran"
}
لاراول 5.7 و 
php: "7.1.3"
چطور باید به شمسی تبدیل کرد؟

**Comment by hekmatinasser** [comment]
از تابع فرمت  استفاده کنید تا به تاریخ شمسی تبدیل شود

**Comment by hekmatinasser** [comment]
وقتی ابجکت را خروجی میگیرید به این شکل نشان میدهد ولی تمامی متد ها به تاریخ شمسی عمل میکند
