### ISSUE TITLE
تبدیل رشته تاریخ شمسی به کربن میلادی

### ISSUE THREAD

**Issue by FaridAghili** [hekmatinasser/verta#21]
سلام
من یک رشته دارم که به شکل زیر هست
`1397/10/22`
می خوام این رو تبدیل به تاریخ میلادی کربن کنم که بتونم در کوئری های لاراول ازش استفاده کنم
بهترین راهش چیه؟

**Comment by hekmatinasser** [comment]
سلام
اول باید پارس کنید  و بعد تبدیل به میلادی کنید
Verta::parse('1397/10/22')->formatGregorian('Y-m-d H:i:s'); // 2019-01-12 00:00:00

**Comment by FaridAghili** [comment]
ممنون، به این شکل عمل کردم، شاید به درد سایرین هم بخوره

```php
$jalaliDate = '1397/10/22';
$gregorianDate= Verta::parse($jalaliDate)->formatGregorian('Y-m-d');
$date = Carbon::parse($gregorianDate);
```

**Comment by hekmatinasser** [comment]
انتها داکیومنت یک کد کوتاه تر هم هست 

$c = Carbon::instance(Verta::parse('1397/10/22')->DateTime());
