### ISSUE TITLE
error on installaiton | ارور هنگام نصب پکیج

### ISSUE THREAD

**Issue by noyalcompany** [hekmatinasser/verta#22]
سلام خسته نباشید 
موقع نصب پکیج این ارور رو دارم

C:\Users\Noyal\Desktop\blog>composer require hekmatinasser/verta

Using version ^1.9 for hekmatinasser/verta
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mysql_xdevapi * is missing from your system. Install or enable PHP's mysql_xdevapi extension.

Installation failed, reverting ./composer.json to its original content.

لطفا بهم کمک کنید

**Comment by hekmatinasser** [comment]
سلام 
این ارور مربوط به پلاگین نیست چون از این ماژول که با عث ارور شده استفاده نمیشه مشکل از این ماژول  
ext-mysql_xdevapi
هست

**Comment by noyalcompany** [comment]
میشه راهنمایی کنید چجوری میشه رفعش کنم؟

**Comment by hekmatinasser** [comment]
داخل فایل 
php.ini
این ماژول را پیدا کنید و بررسی کنید که کامنت است
