### ISSUE TITLE
Undefined offset: -1

### ISSUE THREAD

**Issue by erfantkerfan** [hekmatinasser/verta#25]
- return Verta::parse("1397/12/25")->addMonths(12);

with code above I get this error in leap years:

- Undefined offset: -1

here is traceback:

public static function isValideDate($year, $month, $day) {
        $dayLastMonthJalali = static::isLeapYear($year) && ($month == 12) ? 30 : static::$daysMonthJalali[intval($month)-1];
        return $year >= 1 && $year <= 32766
        && $month >= 1 && $month <= 12
        && $day >= 1 && $day <= $dayLastMonthJalali;
    }

**Comment by hekmatinasser** [comment]
thank you for report .
fix bug this error and release 1.9.10 version
