### ISSUE TITLE
تبدیل نشدن ساعت

### ISSUE THREAD

**Issue by mahdimehrabi** [hekmatinasser/verta#26]
سلام در پکیجتون از هر روشی که برای تبدیل تاریخ میلادی به شمسی استفاده کردم فقط تاریخ رو تبدیل کرد و ساعت رو تبدیل نکرد و همون ساعت میلادی میمونه

**Comment by faryar76** [comment]
what you mean? i think its about timezone in "config/app.php" change it to Asia/Tehran

**Comment by hekmatinasser** [comment]
با سلام منظورتون متوجه نمیشم ساعت بسته به موقعیت زمانی تغییر میکنی همونطور که دوستمون گفتند باید تایم زون خودتون تنطیم کنید
