### ISSUE TITLE
مشکل timezone

### ISSUE THREAD

**Issue by siamak2** [hekmatinasser/verta#27]
سلام
برای عوض کردن تایم زون این کار رو انجام دادم:
$v=verta();
$v->timezone='Asia/Tehran';
ولی تایم زون تغییری نمیکنه و خروجی به صورت
UTC
هست
عملا تغییر این, هیچ تاثیری توی خروجی نداره.
میدونم که میتونم توی
config/app.php
این مقدار رو عوض کنم ولی میخوام همه چی به صورت
UTC
توی دیتابیس سیو بشه و وقتی به کاربر نشون میدم به وقت ایران باشه

**Comment by shahind** [comment]
> سلام
> برای عوض کردن تایم زون این کار رو انجام دادم:
> $v=verta();
> $v->timezone='Asia/Tehran';
> ولی تایم زون تغییری نمیکنه و خروجی به صورت
> UTC
> هست
> عملا تغییر این, هیچ تاثیری توی خروجی نداره.
> میدونم که میتونم توی
> config/app.php
> این مقدار رو عوض کنم ولی میخوام همه چی به صورت
> UTC
> توی دیتابیس سیو بشه و وقتی به کاربر نشون میدم به وقت ایران باشه

me too

**Comment by newvertex** [comment]
@siamak2 , @shahind 
باید تابع رو فراخوانی کنید نه اینکه پراپرتی براش ست کنید!

> $v=verta();
> $v->timezone='Asia/Tehran';  // <== اینجا اشتباه هستش

```php
$v=verta();  
$v->timezone('Asia/Tehran');   // <== تابع تایم زون باید فراخوانی بشه```

**Comment by siamak2** [comment]
@newvertex
توی فایل توضیحات نوشته که میشه به صورت پراپرتی هم بهش مقدار داد
