### ISSUE TITLE
انتخاب فرمت ورودی تاریخ 

### ISSUE THREAD

**Issue by mr-kiani** [hekmatinasser/verta#36]
فرمت تاریخی که من ارسال میکنم برعکسه حالت معمولیه یعنی d/m/Y
توی ورتا چجوری بهش بگم تاریخ به این فرمت برات ارسال میشه

**Comment by mr-kiani** [comment]
خلاصه بگم ، بشه فرمت تاریخ ورودی را مشخص کرد

**Comment by hekmatinasser** [comment]
سلام
تاریخ ورودیتون میلادی هست یا شمسی؟

**Comment by mr-kiani** [comment]
خلاصه بگم ، بشه فرمت تاریخ ورودی را مشخص کرد

> 
> 
> سلام
> تاریخ ورودیتون میلادی هست یا شمسی؟

بصورت شمسی میفرستم سرور
1398/01/01

**Comment by hekmatinasser** [comment]
$v =  Verta::parseFormat('Y/m/d','1398/01/01');
$v =  Verta::parseFormat('d/m/Y','01/01/1398');
