### ISSUE TITLE
Call to undefined method Hekmatinasser\Verta\Verta::startOfDay()

### ISSUE THREAD

**Issue by FaridAghili** [hekmatinasser/verta#4]
`Route::get('/', function () {
    return \Hekmatinasser\Verta\Verta::today();
});`

![image](https://user-images.githubusercontent.com/8607021/34182884-44cd4106-e52d-11e7-97a8-f197f54507e4.png)

**Comment by FaridAghili** [comment]
Using laravel 5.5.26 and PHP 7.2
php intl eneabled

**Comment by hekmatinasser** [comment]
ok 
fix bug now. update to new version 1.8.5
