### ISSUE TITLE
باگ braces is deprecated 

### ISSUE THREAD

**Issue by farazsahebdel** [hekmatinasser/verta#45]
https://github.com/hekmatinasser/verta/blob/0cd5ee45e46709985769025c38915879e57ddc97/src/Verta.php#L1099

https://github.com/hekmatinasser/verta/blob/0cd5ee45e46709985769025c38915879e57ddc97/src/Verta.php#L1101

**Comment by hekmatinasser** [comment]
ok tnx fixed
