### ISSUE TITLE
مشکل نمایش در حلقه

### ISSUE THREAD

**Issue by Parivash-Dehghan** [hekmatinasser/verta#46]
سلام برای تبدیل تاریخ میلادی به شمسی یک آرایه من ازش استفاده میکنم
ولی توی حلقه تبدیل نمیکنه همون میلادی نمایش میده
$ishow['message'][$i]['time'] =new Verta($show[$i]['created_at']);
این کده منه که تبدیل نمیشه

**Comment by erfantkerfan** [comment]
provide some data on:
$show, $i, and the error you get

**Comment by Parivash-Dehghan** [comment]
خطایی نداره
فقط تاریخ رو تبدیل نمیکنه به همون صورت میلادی نمایش میده داخل حلقه ها

**Comment by erfantkerfan** [comment]
پکیج مشکلی نداره من دارم داخل چندین پروژه و داخل حلقه استفاده میکنم سعی کنید داخل tinker امتحان کنید ورودی هاتون رو و ببینید چرا تبدیل نمیکنه یا سعی کنید از این دستور استفاده کنید:
Verta::instance($show[$i]['created_at']);

**Comment by hekmatinasser** [comment]
تاریخ خودتون تبدیل به رشته کنید و بعد داخل ارایه بریزید 
امکان داره چون خود ابجکت داخل ارایه میریزید اینطور نمایش داده میشه

**Comment by MeySamRah** [comment]
i've same problem with verta in collection each() method my code is like this :
`$userDocuments = $user->documents()
            ->with('a_relation')
            ->with('another_one')
            ->get();
        $userDocuments->each(function ($item, $key){
            $item->shamsi_created_at =  Verta::instance($item->created_at);
        });` 
and it returns this
`created_at: "2020-09-09 17:38:12",
shamsi_created_at: {date: "2020-09-09 13:08:12.000000", timezone_type: 1, timezone: "+00:00"}`
