### ISSUE TITLE
problem in addMonths function

### ISSUE THREAD

**Issue by mmasomi73** [hekmatinasser/verta#5]
in addMonths function if date is set begin of month for example : "1396-01-01" and call addMonths  whit number big than 12 in 'Esfand' Month day is incorrect
` if ($month == 12  && !self::isLeapYear($year)) {
                $day--;
   }`
Correct face of this condition is
` if ($month == 12 && $day == 30 && !self::isLeapYear($year)) {
                $day--;
            }`

**Comment by hekmatinasser** [comment]
Tnx fix bug and release new version very tnx

**Comment by FaridAghili** [comment]
@mmasomi73 can you create a PR for this please?

**Comment by mmasomi73** [comment]
@FaridAghili explain more please? your means is Pull Request? :)

**Comment by FaridAghili** [comment]
Yeap

**Comment by mmasomi73** [comment]
it's beautiful that project owner's change & pull  :))

**Comment by hekmatinasser** [comment]
i reales new version with overflow month and without overflow  now. please wait

**Comment by hekmatinasser** [comment]
i release new version with overflow month and without overflow  now. please wait
