### ISSUE TITLE
ext-mysql_xdevapi problem during run composer command

### ISSUE THREAD

**Issue by jamal221** [hekmatinasser/verta#56]
Hello
thanks for useful package, When I run "composer require hekmatinasser/verta" the below error showed and after along time I couldn't to solve it.
Error:"the requested php extension ext-mysql_xdevapi * is missing from your system" 
My Laravel configration is :
Laravel:5.8.35
php:7.1.29
mysql:8.0.12

**Comment by hekmatinasser** [comment]
hi
install ext-mysql_xdevapi extestion php 
[https://www.php.net/manual/en/mysql-xdevapi.installation.php](https://www.php.net/manual/en/mysql-xdevapi.installation.php)
