### ISSUE TITLE
مشکل در تاریخ اسفند سال 1398

### ISSUE THREAD

**Issue by pourshaban** [hekmatinasser/verta#58]
سلام، در کمال تعجب داخل ماه اسفند مشکل وجود داره
مثلا 
    $v = verta();
    $v->year = 1398;
    $v->month = 12;
    $v->day = 18;
    dd($v);

جوابش سال 1399 هست

**Comment by pourshaban** [comment]
تا کی فیکس میشه؟

**Comment by hekmatinasser** [comment]
مشکل از الگوریتم تبدیل تاریخ هست من پلاگین های دیگرو بررسی کردم  همه این مشکل رو دارند و دنبال الگوریتم تبدیل میلادی به شمسی هستم

**Comment by hekmatinasser** [comment]
مشکل از بخاطر این بوده وقتی شما ماه رو تغییر میدید و روی 12 میذارید  سال گذشته کبیسه نبوده  و در الگوریتم تبدیل میشه به اولین روز سال 99
چون کلاس دیتا تایم پی اچ پی  میلادی ما استفاده میکنیم این مشکل پیش نمیاد و در الگوریتم تبدیل میشه به 
اولین روز سال 99

اگر هر سه تا  با هم تنظیم کنید این مشکل پیش نمیاد

**Comment by ehsansabet** [comment]
سلام، این مشکل رو من امروز بهش برخوردم برای ماه های نیمه دوم سال
البته با استفاده از روشی که گفتین، حل شد مشکل، منتهی پیشنهاد میکنم یک جایی در مستندات به این موضوع حتما اشاره کنید
