### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by saber13812002** [hekmatinasser/verta#59]
i have a laravel version 5.2

when i want to install :

> Writing lock file
> Generating autoload files
> > php artisan clear-compiled
> > php artisan optimize
> Generating optimized class loader

This error appeared

PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in .................................\dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php:221   
Stack trace:

dingo-project-management\vendor\symfony\process\Pipes\WindowsPipes.php on line 221
PHP Stack trace:
PHP   1. {main}() C:////projectfolder\artisan:0

  [ErrorException]
  count(): Parameter must be an array or an object that implements Countable    

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by hekmatinasser** [comment]
باسلام

**Comment by hekmatinasser** [comment]
با سلام ایم مشکل ارتباطی با پلاگین تاریخ  ورتا ندارد

**Comment by hekmatinasser** [comment]
این مشکل ارتباطی با پلاگین تاریخ شمسی ندارد
متاسفانه دلیل این مشکل را متوجه  نشدم
