### ISSUE TITLE
PHP >= 7

### ISSUE THREAD

**Issue by Yousha** [hekmatinasser/verta#61]
دوست عزیز، وقتی کتابخونت خودش از کتابخونه هایی استفاده می کنه که فقط روی پی اچ پی **7** یا جدیدتر کار میکنن، کتابخونه شما هم فقط روی پی اچ پی **7** یا جدید تر اجرا میشه

https://packagist.org/packages/illuminate/validation
https://packagist.org/packages/shetabit/helper
...

پس یعنی 
php: >=5.5
غلطه.

**php: ^7.2.5
درسته**

**Comment by hekmatinasser** [comment]
ممنون اصلاح شد
[d80940f](https://github.com/hekmatinasser/verta/commit/d80940f43178d6ab70603539626bd2a2653950cb)
