### ISSUE TITLE
اشتباه تایپی در مستندات فارسی

### ISSUE THREAD

**Issue by aligilan** [hekmatinasser/verta#63]
سلام
در مستندات فارسی، قسمت:
تبدیل تاریخ
برای تبدیل از شمسی به میلادی گفته شده از
getJalali
استفاده بشه
که برعکسه.
یعنی: تبدیل از شمسی به میلادی و برعکسش، جابجا نوشته شده.

**Comment by hekmatinasser** [comment]
ممنون
