### ISSUE TITLE
مشکل با اعداد فارسی

### ISSUE THREAD

**Issue by mohaphez** [hekmatinasser/verta#64]
با سلام ،‌

لطفا قابلیت پارس کردن  اعداد  فارسی رو هم اضافه کنید . 
اگر اعداد فارسی یا عربی بود قابلیت پارس کردن رو هم داشته باشه . 
یبارم اعداد رشته رو به اعداد انگلیسی تبدیل نکنیم . 

در حال حاظر با این خطا مواجه میشیم 

"Unknown datetime '۱۳۹۹/۴/۲۱'"

ممنون

**Comment by hekmatinasser** [comment]
این مورد در این کامیت افزوده شد 
[97ebd19](https://github.com/hekmatinasser/verta/commit/97ebd19568e70135f2cf4218fc4c5cbb67c34e8a)
