### ISSUE TITLE
مشکل PHP Recoverable fatal error در هنگام نصب پکیج

### ISSUE THREAD

**Issue by farsh4d** [hekmatinasser/verta#66]
سلام
من دستور composer install رو برای نصب میزنم هنگام نصب پیام خطا زیر رو میده:
`PHP Recoverable fatal error:  Object of class DateTime could not be converted to string in ...\vendor\hekmatinasser\verta\src\Verta.php on line 1457`
ورژن لاراول: 5.4

**Comment by hekmatinasser** [comment]
fix bug v.1.10.6
