### ISSUE TITLE
خطا در محاسبه اختلاف دو تاریخ 

### ISSUE THREAD

**Issue by mohaphez** [hekmatinasser/verta#68]
با سلام و خسته نباشید 

من میخوام اختلاف دو تاریخ رو در بیارم  ولی اشتباه محاسبه میکنه  

تاریخ اول هست :  
۱۳۹۹/۰۱/۰۱
تاریخ دوم : 
۱۳۹۹/۰۵/۰۸

که اختلاف اینا  میشه  
۳۱*۴ +۸ = ۱۳۲ 
ولی جواب ۱۲۷ میده  

مستندات  پیوست میکنم خدمتتون 

![Screenshot_2020-07-29_13-10-31](https://user-images.githubusercontent.com/20874565/88778260-8898b000-d19d-11ea-8615-f080ba34effc.png)
![Screenshot_2020-07-29_13-15-43](https://user-images.githubusercontent.com/20874565/88778324-a239f780-d19d-11ea-8d05-7a4d38b2f2b2.png)

**Comment by hekmatinasser** [comment]
منم همین تابع رو اجرا کردم  خروجی 131 شد که درسته چون خود روز ا فرودین نباید حساب کنید
$v1 = Verta::parse('1399-01-01');
    $v2 = Verta::parse('1399-05-08');
    dd($v1,$v2, $v1->diffDays($v2));
Verta @1584662400 {#270 ▼
  date: 1399-01-01 00:00:00.0 UTC (+00:00)
}

Verta @1595980800 {#276 ▼
  date: 1399-05-08 00:00:00.0 UTC (+00:00)
}

131

**Comment by mohaphez** [comment]
بله با این متدی که شما نوشتید تست کردم درست شد . 

ولی کدی که بالا نوشتم واقعا ۱۲۷ میداد 

حالا فرقش در چیست واقعا نمیدونم 

در هر صورت ممنون از راهنمایی و پیگیری شما 

موفق باشید
