### ISSUE TITLE
نمایش عدد ماه های تک رقمی بدون صفر قبل از آن

### ISSUE THREAD

**Issue by mizogii** [hekmatinasser/verta#7]
سلام دوستان از پکیج ورتا استفاده میکنم و اتفاقی که میافته اینه که تاریخ رو وقتی به شمسی تبدیل میکنه ماه هایی که تک رقمی هستن رو صفر قبل عدد رو نمیذاره مثلا بجای اینکه تاریخ رو اینطوری 1397/02/15 نشون بده اینطوری 1397/2/15 نشون میده چیکار کنم که این عدد ماه رو بصورت 02 نشون بده. آپدیت جدیدی از این پکیج هست که این کارو انجام بده؟

**Comment by mizogii** [comment]
این مشکل رو با اضافه کردن 
"%02d", $date[1]) 
به کد زیر برطرف کردم

public function toPersian($date)
    {
        $gDate = $date;
        if ($date = explode('-', $gDate)) {
            $year  = $date[0];
            $month = $date[1];
            $day   = $date[2];
        }
        $date = Verta::getJalali($year, $month, $day);
        $myDate = $date[0] . '/' . sprintf("%02d", $date[1]) . '/' . sprintf("%02d", $date[2]);
        return $myDate;
    }

**Comment by hekmatinasser** [comment]
کاربر گرامی نیازی به تغییر کد های ورتا ندارید برای اینکه 0 قبل ماه های تک رقمی رو نمیخواهید نشون بده از این دستور استفاده کنید.
return $v->format('Y-n-j H:i'); // 1395-10-7 14:12

**Comment by MahdiPishguy** [comment]
> 
> 
> کاربر گرامی نیازی به نوشتن تابع ندارید برای اینکه 0 قبل ماه های تک رقمی رو نمیخواهید نشون بده از این دستور استفاده کنید.
> return $v->format('Y-n-j H:i'); // 1395-10-7 14:12

ایشون گفتن عدد صفر رو برای قبل اعداد تک رقمی ماه و روز نمیزاره نگفتن که چرا میزاره. بنابراین به نظر میرسه پاسخ شما اشتباه هستش و الان سوال این هستش که چطور اعداد صفر رو قبل این تک رقمی ها بزاریم؟

**Comment by MahdiPishguy** [comment]
> 
> 
> این مشکل رو با اضافه کردن
> "%02d", $date[1])
> به کد زیر برطرف کردم
> 
> public function toPersian($date)
> {
> $gDate = $date;
> if ($date = explode('-', $gDate)) {
> $year = $date[0];
> $month = $date[1];
> $day = $date[2];
> }
> $date = Verta::getJalali($year, $month, $day);
> $myDate = $date[0] . '/' . sprintf("%02d", $date[1]) . '/' . sprintf("%02d", $date[2]);
> return $myDate;
> }

```php
public function toPersian($date)
{
    $date = explode('-', Verta::instance($date)->format('Y-n-j'));
    return $date[0] . '/' . sprintf("%02d", $date[1]) . '/' . sprintf("%02d", $date[2]);
}
```
