### ISSUE TITLE
تبدیل تاریخ

### ISSUE THREAD

**Issue by ahmadmhm** [hekmatinasser/verta#76]
سلام
ما در پروژه مون از verta استفاده کردیم و تا الان هم درست بوده
ولی مدتیه که موقع نمایش داره ساعت رو اشتباه میزنه
در دیتابیس timezone و ... درست هستش ولی موقع نمایش
ساعتش 3:30 کمتر نشون میده
ممنون میشم یه چک بفرمایید

**Comment by ali-pedram** [comment]
این مشکل برای من هم در آخرین آپدیت به وجود اومده

**Comment by ahmadmhm** [comment]
سلام آره نمیدونم چرا، فعلا که هنوز جوابی ندادن

**Comment by mma56k** [comment]
سلام به همه
برای من هم همین مشکل هست

        dd(
            verta($student->created_at),
            verta()->setTimezone(new \DateTimeZone("Asia/Tehran")),
            verta()->timezone('Asia/Tehran'),
            verta($student->created_at)->timeZone('Asia/Tehran'),
            verta($student->created_at),

        );
ولی بازم ساعت رو اشتباه می نویسه

**Comment by mohammadsalmani28** [comment]
سلام من هم این مشکل رو دارم 
`verta($person->created_at)->timezone('Asia/Tehran')->format('H:i y/m/d'),`

از تایم زون به این شکل مجبور شدم استفاده کنم

**Comment by hekmatinasser** [comment]
سلام این مورد بررسی میکنم

**Comment by hekmatinasser** [comment]
> سلام
> ما در پروژه مون از verta استفاده کردیم و تا الان هم درست بوده
> ولی مدتیه که موقع نمایش داره ساعت رو اشتباه میزنه
> در دیتابیس timezone و ... درست هستش ولی موقع نمایش
> ساعتش 3:30 کمتر نشون میده
> ممنون میشم یه چک بفرمایید

کدتون رو بفرستید تا بررسی کنم

**Comment by mma56k** [comment]
dd(
        Verta::parse('1399-08-14'),
        now(),
    );
---------------------
^ Hekmatinasser\Verta\Verta @1604435400 {#2046 ▼
  date: 1399-08-13 20:30:00.0 +00:00
}

^ Illuminate\Support\Carbon @1604480297 {#2044 ▼
  date: 2020-11-04 12:28:17.136471 Asia/Tehran (+03:30)
}

**Comment by hekmatinasser** [comment]
fix bug in new [version 1.11.1](https://github.com/hekmatinasser/verta/tree/v1.11.1)

**Comment by amirzpr** [comment]
سلام. این مشکل بعد از
bug fix v1.11.1
همچنان وجود داره و باید 
timezone 
رو ست کرد. وگرنه تایم رو به 
UTC
نشون میده

**Comment by hekmatinasser** [comment]
مشکل حل شد نسخه جدید تر  نصب کنید

**Comment by amirzpr** [comment]
من روی نسخه 1.11.4 این مشکل رو دارم که در حال حاضر آخرین نسخه است

**Comment by AliKhedmati** [comment]
سلام
بنده هم در ورژن 1.11.7 دقیقاً همین مشکل رو دارم.
ممنون میشم بررسی کنین.
