### ISSUE TITLE
remove persianNumber()  method

### ISSUE THREAD

**Issue by rashidsiavoshi** [hekmatinasser/verta#78]
if (! function_exists('en_to_fa')) {
    /**
     * Convert english digits to farsi.
     *
     * @param string $text
     * @return string
     */
    function en_to_fa($text)
    {
        $en_num = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
        $fa_num = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];

        return str_replace($en_num, $fa_num, $text);
    }
}

if (! function_exists('fa_to_en')) {
    /**
     * Convert farsi/arabic digits to english.
     *
     * @param string $text
     * @return string
     */
    function fa_to_en($text)
    {
        $fa_num = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹', '٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
        $en_num = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

        return str_replace($fa_num, $en_num, $text);
    }
}

please add this functions instead of persianNumber() method , persianNumber() was deleted and  I can't find it

**Comment by hekmatinasser** [comment]
persianNumber is deprecate method and replace with enToFaNumbers
