### ISSUE TITLE
اشتباه در تبدیل تاریخ از شمسی به میلادی

### ISSUE THREAD

**Issue by msabiloo** [hekmatinasser/verta#79]
ایتدا یک تاریخ شمسی در یک متغیر ذخیره کردم
`$date = '1399-08-17'`
بعد از متد parse استفاده کردم و نتیجه را در متغیر دیگری ذخیره کردم
`$parsedDate = Verta::parse($date)`
خروجی به شکل زیر نمایش داده شد
`Hekmatinasser\Verta\Verta @1604694600 {#4477
     date: 1399-08-17 00:00:00.0 Asia/Tehran (+03:30),
   }`
در نهایت با متد formatGregorian تاریخ را از شمسی به میلادی تغییر دادم
`$parsedDate->formatGregorian('Y-m-d');`
خروجی به شکل زیر نمایش داده شد
`"2020-11-06"`
در صورتی که خروجی مورد انتظار می‌بایست به شکل زیر باشد
`"2020-11-07"`

![image](https://user-images.githubusercontent.com/21129970/98435713-7e664600-20ea-11eb-9912-c7de2802eece.png)

**Comment by msabiloo** [comment]
توضیح اینکه منطقه زمانی ایران هست

**Comment by hekmatinasser** [comment]
سلام ممنون بررسی میکنم

**Comment by hekmatinasser** [comment]
درنسخه جدید 1.11.2 رفع شد
