### ISSUE TITLE
مشکل در تبدیل تاریخ

### ISSUE THREAD

**Issue by alifattahi** [hekmatinasser/verta#80]
سلام
در تبدیل تاریخ مشکل وجود داره.
توابع زیر کار نمیکنه
formatGregorian('Y-m-d H:i:s')
قبلا تابع $v->startDay()->DateTime() تاریخ میلادی میداد الان شمسی میده. 
ممنون میشم رفعش کنید.

**Comment by AmirFayaz** [comment]
برای من هم مشکل خورده 
Verta::parse('1399-08-18 20:49:33')->formatGregorian('Y-m-d H:i:s');
این قبلا خروجی میلادی میداد ولی الان شمسی میده

**Comment by MahdiPishguy** [comment]
@alifattahi @AmirFayaz 

شما هم تو لاراول ۸ به این مشکل برخوردید؟ تو لاراول ۷ درست بود؟ من به تازگی رفتم روی ۸ یه چند تا مشکل جدید پیش اومده

**Comment by AmirFayaz** [comment]
@MahdiPishguy 
من با لومن ۷ کار میکنم
امروز پکیج ها رو آپدیت کردم اینطوری شد
فکر کنم آپدیت جدید باگ داره

**Comment by hekmatinasser** [comment]
بررسی میکنم

**Comment by hekmatinasser** [comment]
مشکل مرتفع شد نسخه 1.11.3
