### ISSUE TITLE
Unknown datetime 'XXXXXX'

### ISSUE THREAD

**Issue by MahdiPishguy** [hekmatinasser/verta#81]
```
Verta($post->created_at)->format('%d %B %Y')
Verta($message->created_at)->formatDifference()
```

این دستورها الان تو لاراول ۷ به خوبی کار میکنن ولی الان خطای زیر رو میده

```
Unknown datetime 'XXXXXX'
```

> "hekmatinasser/verta": "^1.11.2",

خروجی متغیر 
`$message->created_at`

```
2020-11-08 22:39:42
```

**Comment by hekmatinasser** [comment]
بررسی میکنم

**Comment by hekmatinasser** [comment]
return verta('2020-11-08 22:39:42')->formatDifference();

11 ساعت قبل

**Comment by MahdiPishguy** [comment]
@hekmatinasser 

وقتی که خود متغیر $message->created_at رو چاپ میکنیم تاریخی که تو پست اول گذاشتم رو نشون میده

حالا وقتی که همون متغیر رو میخاییم با کتابخونه تبدیل کنیم اون رو به تایم استمپ نشون میده و خطا میده. در واقع این رو داریم از دیتابیس ستون created_at رو بهش میدیم. چندین بار تست کردم تو لاراول ۷ کاملا درسته و الان هم روی سایتمون داره کار میکنه
 
ولی الان که برنچ دیگه ای داریم همین دستور تو لاراول ۸ داره این خطا رو میده

**Comment by hekmatinasser** [comment]
اوکی چک میکنم

**Comment by FaridAghili** [comment]
@hekmatinasser 

در خط زیر:
https://github.com/hekmatinasser/verta/blob/cd4197514d80cfadecd626d40ac296991ca6d7e1/src/Traits/Creator.php#L31

تغییر زیر رو اعمال کنید:
```diff
- $datetime = $datetime->getTimestamp();
+ $datetime = '@'.$datetime->getTimestamp();
```

**Comment by FaridAghili** [comment]
یه مورد دیگه اینکه
&#x202b; آیا اصلا نیازه وقتی مقدار متغیر `datetime` از نوع `DateTimeInterface` هست اونو به Timestamp تبدیل کنیم؟

بعد از حذف این ۳ خط هم به درستی کار می‌کنه

```diff
public function __construct($datetime = null, $timezone = null)
{
    if(empty($datetime)) {
        $datetime = 'now';
    }
    elseif (is_string($datetime)) {
        $datetime = self::faToEnNumbers(self::arToEnNumbers($datetime));
    }
-    elseif ($datetime instanceof DateTimeInterface) {
-        $datetime = $datetime->getTimestamp();
-    }
    elseif (is_int($datetime)) {
        $datetime = "@$datetime";
    }

    try {
        parent::__construct($datetime, static::createTimeZone($timezone));
    } catch (Exception $exception) {
        throw new InvalidArgumentException(sprintf("Unknown datetime '%s'", $datetime));
    }
}
```

**Comment by hekmatinasser** [comment]
> یه مورد دیگه اینکه
> ‫ آیا اصلا نیازه وقتی مقدار متغیر `datetime` از نوع `DateTimeInterface` هست اونو به Timestamp تبدیل کنیم؟
> 
> بعد از حذف این ۳ خط هم به درستی کار می‌کنه
> 
> ```diff
> public function __construct($datetime = null, $timezone = null)
> {
>     if(empty($datetime)) {
>         $datetime = 'now';
>     }
>     elseif (is_string($datetime)) {
>         $datetime = self::faToEnNumbers(self::arToEnNumbers($datetime));
>     }
> -    elseif ($datetime instanceof DateTimeInterface) {
> -        $datetime = $datetime->getTimestamp();
> -    }
>     elseif (is_int($datetime)) {
>         $datetime = "@$datetime";
>     }
> 
>     try {
>         parent::__construct($datetime, static::createTimeZone($timezone));
>     } catch (Exception $exception) {
>         throw new InvalidArgumentException(sprintf("Unknown datetime '%s'", $datetime));
>     }
> }
> ```

بله در مواردی هست ورودی تاریخ و زمان پی اچ پی و این خط قابل حذف نیست

**Comment by hekmatinasser** [comment]
در نسخه جدید مرتفع شد v1.11.4
