### ISSUE TITLE
مشکل با php8

### ISSUE THREAD

**Issue by majidlx67** [hekmatinasser/verta#85]
سلام
من یک پروژه
Laravel 8
با
PHP 8
ایجاد کردم.
وقتی می خواستم پکیج را نصب کنم با خطای زیر مواجه شدم:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hekmatinasser/verta[v1.10.0, ..., v1.10.3] require illuminate/validation ^5|^6 -> found illuminate/validation[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with another require.
    - hekmatinasser/verta v1.10.4 requires illuminate/validation ^5|^6|^7 -> found illuminate/validation[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - hekmatinasser/verta[v1.10.5, ..., v1.11.6] require php ^7.2.5 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires hekmatinasser/verta ^1.10 -> satisfiable by hekmatinasser/verta[v1.10.0, ..., v1.11.6].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by FaridAghili** [comment]
https://github.com/hekmatinasser/verta/blob/fbb9f3be316c65c7528895775d71cc3592475e9d/composer.json#L13

خط فوق به شکل زیر ویرایش شود:
`"php": "^7.2.5|^8.0",`

**Comment by hekmatinasser** [comment]
support php 8
