### ISSUE TITLE
اعتبار سنجی تاریخ

### ISSUE THREAD

**Issue by samadha56** [hekmatinasser/verta#87]
تو فرم یک تاریخ شمسی از طریق
persian data picker
انتخاب میشه، اما در اعتبار سنجی با 
jdate:Y/m/d
میگه تاریخ شمسی معتبر نیست!
تاریخ شمسی که
request
دریافت میکنه به شکل زیر است:
۱۳۹۹/۰۹/۲۴

**Comment by rezatati** [comment]
سلام من هم این مشکل رو داشتم میتونین از این تابع استفاده کننین که اعداد رو به انگلیسی تبدیلش کننین

function toEnglishNumbers(String $string): String
{

	$persinaDigits1 = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];

	$persinaDigits2 = ['٩', '٨', '٧', '٦', '٥', '٤', '٣', '٢', '١', '٠'];

	$allPersianDigits = array_merge($persinaDigits1, $persinaDigits2);

	$replaces = [...range(0, 9), ...range(0, 9)];

	return str_replace($allPersianDigits, $replaces, $string);
}

**Comment by samadha56** [comment]
@rezatati ممنون، من علاوه بر کد شما یک Rule به شکل زیر درست کردم و موقع اعتبار سنجی اون رو صدا میکنم:

`<?php

namespace App\Rules;

use App\Components\Helper;
use Illuminate\Contracts\Validation\Rule;
use Verta;

class ShamsiDate implements Rule
{
    /**
     * Create a new rule instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        try {
            $standard_char = Helper::persianToEnglishNumber($value);
            $date = explode('/', $standard_char);
            return Verta::isValidDate($date[0], $date[1], $date[2]);
        } catch (\Throwable $th) {
            return false;
        }
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'فرمت :attribute مطابق با تاریخ شمسی نمی باشد.';
    }
}
`
