### ISSUE TITLE
instantiation with unix timestamp

### ISSUE THREAD

**Issue by khmohamad79** [hekmatinasser/verta#89]
this line doesn't work and throws an exception:
`$v = new Verta(1607632198);`
![image](https://user-images.githubusercontent.com/19171363/102117307-673a1700-3e53-11eb-8587-c363c4b41dbd.png)

I traced the execution path and realized that there is a mistake in the first line of Verta constructor.
str_replace is being used in arToEnNumbers method and it is forgotten that str_replace casts integer to string!
so, $datetime will always be string-type and this condition:
`elseif (is_numeric($datetime)) {...}`
never will be checked.

**Comment by hekmatinasser** [comment]
test timestamp return 1399-09-20 23:59:58
