### ISSUE TITLE
مشکل نمایش شماره هفته در سال

### ISSUE THREAD

**Issue by ahjamshidi** [hekmatinasser/verta#9]
با سلام
در ابتدا از زحماتتون تشکر میکنم 
میخواستم بگم تو بخش محاسبه شماره هفته در سال یه اشتباه وجود داره 
تو تابع زیر چون تعداد روز های ماه داده شده نباید محاسبه بشه 
`    protected function daysYear($month, $day) {
        $days = 0;
        for ($i = 0; $i < ($month-1); $i ++) {
            $days += static::$daysMonthJalali[$i];
        }
        return ($days + $day);
    }`

**Comment by hekmatinasser** [comment]
باسلام

**Comment by hekmatinasser** [comment]
باسلام
ممنون 
اگر موردی وجود دارد ورودی و خروجی کد خود را بفرستید تا بررسی کنم
باتشکر

**Comment by hekmatinasser** [comment]
thank for report.
fixbug method daysYear and you can update verta v1.9.5.

**Comment by UpwardProcess** [comment]
Just as a note, your latest commit is introducing another bug, ignoring the first month of the year since you start your index from 1 now.
