### ISSUE TITLE
Verta constructor ignores the timezone!

### ISSUE THREAD

**Issue by hrvali** [hekmatinasser/verta#91]
When you create verta with below statement

   ```
$dt = new \Datetime();
   return new Verta($dt);
```

Although the timestamp must be taken from the config, it is set to UTC, Even with the following command, timezone is not considered:

```
$dt = new \Datetime();
return new Verta($dt, 'Asia/Tehran');
```

It is because in __construct method(as I copied it below), you convert the argument to timestamp and then call parent constructor with that timestamp and the related timezone, 

    public function __construct($datetime = null, $timezone = null)
    {
        if(empty($datetime)) {
            $datetime = 'now';
        }
        elseif (is_string($datetime)) {
            $datetime = self::faToEnNumbers(self::arToEnNumbers($datetime));
        }
        elseif ($datetime instanceof DateTime) {
            $datetime = "@{$datetime->getTimestamp()}";
        }
        elseif (is_int($datetime)) {
            $datetime = "@$datetime";
        }

        try {
            parent::__construct($datetime, static::createTimeZone($timezone));
            // parent::setTimezone(new DateTimeZone('Asia/Tehran'));
            debug('parent', parent::format('Y-m-d H:i:s e'));
        } catch (Exception $exception) {
            throw new InvalidArgumentException(sprintf("Unknown datetime '%s'", $datetime));
        }
    }

As noted in the [php doc](https://www.php.net/manual/en/datetime.construct.php) the constructor of DateTime(the parent), does not consider timezone when you send a timestamp to it:

> Note:
The $timezone parameter and the current timezone are ignored when the $datetime parameter either is a UNIX timestamp (e.g. @946684800) or specifies a timezone (e.g. 2010-01-28T15:00:00+02:00).

So the solution can be something like:
parent::__construct($datetime);
parent::setTimezone(static::createTimeZone($timezone));

Thanks in advance

**Comment by mssayari** [comment]
I just came to create Issue about why Verta shows wrong Timezone, even though I change it in config file.
should I create PR for this ?
