### ISSUE TITLE
ادغام با سایر فریمورک ها

### ISSUE THREAD

**Issue by Azoic** [hekmatinasser/verta#94]
سلام دوست عزیز
من این پکیج رو با فریمورک Yii2 استفاده کردم خیلی هم عالی بود
برای همین پیشنهادی داشتم
اینکه شاید با یکم تغییرات بشه بصورت کامل برای تمام فریمورک ها ازش استفاده کرد و یا اینکه با استانداردهای PSR طراحی کنید تا هر فریمورکی با این استاندارد بود باهاش کار کنه
البته الان هم کار میکنه صرفا لازمه شما توی متن مختص بودن به لاراول رو حذف کنید!
پکیج های مشابهی مثل morilog/jalali رو هم بررسی کردم اما پکیج شما رو کاملتر دیدم اما برتری اون به پکیج شما همین موردی بود که عرض کردم

**Comment by hekmatinasser** [comment]
بله حتما بررسیی خواهم کرد و  ساز گاری با سایر فریم ورک ها انجام خواهم داد
خودتون هم میتونید کمک کنید و پول ریکوئست بدید

**Comment by hekmatinasser** [comment]
در حال این کار هستم اما به مرور این اتفاق خواهد افتاد

**Comment by hekmatinasser** [comment]
پکیج نسخه جدید با همه فریم ورک های سازگار هست  ورتا مخصوص  لاراول و پکیج جلالی مخصوص php منتشر شده. 
[https://github.com/hekmatinasser/jalali](url)
