### ISSUE TITLE
startMonth & endMonth

### ISSUE THREAD

**Issue by meysam2594** [hekmatinasser/verta#96]
hi there , thanks for your grate library . have some issue with startMonth and endMonth function .
today date in jalalian is : 1400/01/30 but when use startMonth and endMonth return 1400/02/01 and 1400/02/31 , how can fix that

**Comment by hekmatinasser** [comment]
hi thanks you for issue
check and fix coming soon

**Comment by hekmatinasser** [comment]
test this issue in date 1400/01/30 startMonth and endMonth return 1400/01/01 and 1400/01/31

send detail timezone project for solve problem
