### ISSUE TITLE
how to convert persian  date string  to gregorian

### ISSUE THREAD

**Issue by bobper** [hekmatinasser/verta#98]
This is input of "۱۴۰۰-۰۲-۲۱" babakhani js date picker
how to convert this string to gregorian date 
for now we must do this step
$start_time = "۱۴۰۰-۰۲-۲۱";
 $arr = explode('-' , Verta::faToEnNumbers($start_time)); 
 $gregorianArray  = Verta::getGregorian((int)$arr[0] ,(int) $arr[1] , (int)$arr[2]) ;
  $gregorianDate  = implode('-' ,$gregorianArray);
it's better this be a function
thanks

**Comment by hekmatinasser** [comment]
you can use
Verta::parse("۱۴۰۰-۰۲-۲۱")->formatGregorian('Y-m-d);
