### ISSUE TITLE
Add support for other names for months

### ISSUE THREAD

**Issue by ahangarha** [hekmatinasser/verta#99]
Aghans use the same calendar as Iranians do but they use different names for months. It would be good to add some config for choosing which month name to use. The default could be Iranian names but user can change it either using config or even locale.

It can be extended in such a way that user can choose other names as well. List of different name can be seen here: [گاه‌شماری هجری خورشیدی](https://fa.wikipedia.org/wiki/%DA%AF%D8%A7%D9%87%E2%80%8C%D8%B4%D9%85%D8%A7%D8%B1%DB%8C_%D9%87%D8%AC%D8%B1%DB%8C_%D8%AE%D9%88%D8%B1%D8%B4%DB%8C%D8%AF%DB%8C)

![image](https://user-images.githubusercontent.com/11241315/117535515-65900c00-b00b-11eb-982f-baa73a9a086b.png)

**Comment by ahangarha** [comment]
نمی‌دونم شیوه صحیح افزودن چنین تنظیمی به چنین پروژه‌ای چیست. مگر نه مشارکت می‌کردم. الان هم امیدوارم بتونم چیزی یاد بگیرم

**Comment by hekmatinasser** [comment]
در حال افزودن این مورد به پروژه هستم

**Comment by hekmatinasser** [comment]
نسخه 1.12 با افزودن سه زبان اضافه شد به زودی زبان های دیگر نیز به پروژه اضافه خواهند شد
